# Greetings and goodbyes messages
greetings = ["Hello!", "What's up?!", "Howdy!", "Greetings!"]
goodbyes = ["Bye!", "Goodbye!", "See you later!", "See you soon!"]
questions = [
    "How was your day?",
    "Did you code anything interesting recently?",
    "Any new programming languages you've tried?",
    "What’s your favorite programming language?",
    "What coding projects are you working on?",
    "Tried any new libraries or frameworks?",
    "How do you debug when errors pop up?",
    "What’s a coding challenge you’re proud of?",
    "Contributed to any open-source projects?",
    "Favorite editor or IDE for coding?",
    "Built a game or simulation before?",
    "How do you manage version control?",
    "Any cool coding ideas lately?",
    "Do you prefer frontend or backend development?",
    "What’s a piece of code you love?",
    "Most complex project you've worked on?",
    "How do you stay motivated during tough projects?",
    "Worked with any AI or machine learning libraries?",
    "Do you like writing tests for your code?",
    "Explored any new tech or tools recently?",

    "Highlight of your week?",
    "How are you feeling today?",
    "Any personal goals you're working on?",
    "What’s your biggest passion outside coding?",
    "What’s been on your mind lately?",
    "What are you excited about right now?",
    "What made you smile recently?",
    "How do you like to start your day?",
    "What are you looking forward to this month?",
    "Most rewarding project recently?",
    "Do you have a favorite relaxation spot?",
    "What’s been on your mind lately?",
    "Last time you did something fun?",
    "How do you unwind after a long day?",
    "Any fun plans lately?",
    "Dream travel destination?",
    "Best advice you've ever received?",
    "How do you stay motivated during hard times?",
    "What’s a recent goal you've achieved?",
    "Interesting thing you’ve learned recently?",

    "Favorite hobby outside coding?",
    "How do you relax?",
    "Most fun project you’ve done?",
    "Any upcoming travel plans?",
    "How do you spend your weekends?",
    "Fun memory from last week?",
    "How’s your work-life balance?",
    "What do you do for fun?",
    "Any new interests outside coding?",
    "Something fun you did recently?",
    "Skill you're working on outside tech?",
    "How's your week been so far?",
    "Activities you do when stressed?",
    "Do you prefer working alone or in a team?",
    "Place that helps you focus while coding?",
    "Favorite way to relax after a long day?",
    "What do you enjoy reading or watching?",
    "Favorite way to stay productive?",
    "Personal project you're excited about?",
    "Small change that improved your life?",

    "Feel like time passes differently when coding?",
    "Anything random made you laugh lately?",
    "What are you looking forward to today?",
    "Advice for your past self?",
    "Favorite way to start the day?",
    "Do you daydream while coding?",
    "Weirdest thing encountered in a project?",
    "Any surprises this week?",
    "How's your coding journey going?",
    "If you could change one thing about today?",
    "Ever stare at code and think about life?",
    "One thing you wish you had more time for?",
    "How has coding changed your life?",
    "Talked to your code out loud before?",
    "Habit you’re trying to break?",
    "If your code could talk, what would it say?",
    "Ever feel like a project has a life of its own?",
    "What would you be doing if not coding?",
    "What have you learned about yourself through coding?",
    "Where do you think you'll be in 5 years?",

    "Recent challenge and how you're handling it?",
    "If you had more time, what hobby would you dive into?",
    "Has coding changed your world view?",
    "Moment you felt proud of yourself recently?",
    "Something you've meant to start but haven’t?",
    "If you could master a skill instantly, what would it be?",
    "What’s been making you happy lately?",
    "Had any ‘aha’ moments with coding recently?",
    "Any coding rituals that help you focus?",
    "Project you’ve always wanted to start?",
    "Anything you’d like to improve in your routine?",
    "How do you stay inspired on long projects?",
    "Curiosity outside coding?",
    "Catch yourself thinking about code off-screen?",
    "Balancing work and personal time?",
    "Recent personal achievement you're proud of?",
    "What brings you joy each day?",
    "Need a break from technology?",
    "Where would you go on a vacation right now?",

    "What made you smile today?",
    "Tried any new hobbies lately?",
    "How's everything going?",
    "What are you looking forward to this week?",
    "New favorite spots to relax or work?",
    "Small win you've had recently?",
    "What are you passionate about these days?",
    "How do you stay motivated during tough times?",
    "Best part of your day?",
    "Something you've been meaning to start?",
    "Most exciting part of your week?",
    "How do you spend your free time?",
    "Curious about anything lately?",
    "How’s your month going?",
    "Discovered any new music or shows?",
    "What are you proud of right now?",
    "Any upcoming plans you're excited about?",
    "Most fun you've had this month?",
    "Tried anything new lately?",
    "Working on a new habit?"
]


other_responses = [
    "Tell me more!",
    "Go on!",
    "Please continue.",
    "I’d love to hear more.",
    "What else do you think?",
    "That makes sense. I’m listening.",
    "Keep sharing!",
    "You have my attention.",
    "Great point! What’s next?",
    "I love this! Keep going.",
    "Absolutely! What else?",
    "Tell me more about that!",
    "I appreciate your thoughts—let’s chat.",
    "What’s next on your mind?",
    "I’m following you—keep going!",
    "That’s interesting! What else?",
    "I’m intrigued—continue!",
    "What else do you have in mind?",
    "You’ve piqued my interest—share more!",
    "Your perspective is valuable—let’s discuss.",
    "Engaging conversation! What’s on your mind?",
    "Great insights! What else can you share?",
    "Compelling! What’s next?",
    "Very interesting! Please go on.",
    "Thought-provoking! Eager for more.",
    "Great expression! Let’s keep this going.",
    "That resonates! Let’s dive deeper.",
    "Captivating! Please, share more.",
    "Delightful exchange! What’s next?"
]